# Generated by Django 3.0.3 on 2020-02-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('homeAddress', models.TextField(max_length=255, null=True)),
                ('medicalSchool', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('contactNumber', models.CharField(max_length=200, null=True)),
                ('specialization', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
