# Generated by Django 3.0.3 on 2020-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
