# Generated by Django 3.0.3 on 2020-02-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('homeNumber', models.CharField(max_length=100, null=True)),
                ('homeAddress', models.TextField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('postal', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('birthDate', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True)),
                ('maritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Legally Seperated', 'Legally Seperated'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('medications', models.TextField(blank=True, max_length=300)),
                ('medicalDirectives', models.TextField(blank=True, max_length=300)),
                ('medicalProblems', models.TextField(blank=True, max_length=300)),
                ('vitalSigns', models.TextField(blank=True, max_length=300)),
                ('physicalExam', models.TextField(blank=True, max_length=300)),
                ('medicalHistory', models.TextField(blank=True, max_length=300)),
                ('medicationPlan', models.TextField(blank=True, max_length=300)),
                ('medicalOrders', models.TextField(blank=True, max_length=300)),
                ('alkPhos', models.CharField(blank=True, max_length=10)),
                ('bun', models.CharField(blank=True, max_length=10)),
                ('calcium', models.CharField(blank=True, max_length=10)),
                ('chloride', models.CharField(blank=True, max_length=10)),
                ('co2', models.CharField(blank=True, max_length=10)),
                ('creatinine', models.CharField(blank=True, max_length=10)),
                ('po4', models.CharField(blank=True, max_length=10)),
                ('potassium', models.CharField(blank=True, max_length=10)),
                ('sgot', models.CharField(blank=True, max_length=10)),
                ('biliTotal', models.CharField(blank=True, max_length=10)),
                ('uricAcid', models.CharField(blank=True, max_length=10)),
                ('ldhTotal', models.CharField(blank=True, max_length=10)),
                ('sodium', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('temperature', models.CharField(blank=True, max_length=10)),
                ('tempSite', models.CharField(blank=True, max_length=10)),
                ('pulseRate', models.CharField(blank=True, max_length=10)),
                ('pulseRhytm', models.CharField(blank=True, max_length=10)),
                ('respRate', models.CharField(blank=True, max_length=10)),
                ('bpSystolic', models.CharField(blank=True, max_length=10)),
                ('bpDiastolic', models.CharField(blank=True, max_length=10)),
                ('cholesterol', models.CharField(blank=True, max_length=10)),
                ('hdl', models.CharField(blank=True, max_length=10)),
                ('ldl', models.CharField(blank=True, max_length=10)),
                ('bgRandom', models.CharField(blank=True, max_length=10)),
                ('cxr', models.CharField(blank=True, max_length=10)),
                ('ekg', models.CharField(blank=True, max_length=10)),
                ('papSmear', models.CharField(blank=True, max_length=10)),
                ('breastExam', models.CharField(blank=True, max_length=10)),
                ('mammogram', models.CharField(blank=True, max_length=10)),
                ('hemoccult', models.CharField(blank=True, max_length=10)),
                ('fluVax', models.CharField(blank=True, max_length=10)),
                ('pneumovax', models.CharField(blank=True, max_length=10)),
                ('tdBooster', models.CharField(blank=True, max_length=10)),
                ('footExam', models.CharField(blank=True, max_length=10)),
                ('eyeExam', models.CharField(blank=True, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
