# Generated by Django 3.0.3 on 2020-02-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='genericName',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Neurology', 'Neurology'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Cardiology', 'Cardiology'), ('Laboratory', 'Laboratory'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Radiology', 'Radiology'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Nephrology', 'Nephrology'), ('Sterilization', 'Sterilization'), ('Surgery', 'Surgery'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Anaesthesiology', 'Anaesthesiology')], max_length=100, null=True),
        ),
    ]
