# Generated by Django 3.0.3 on 2020-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200226_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='genericName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Anaesthesiology', 'Anaesthesiology'), ('Radiology', 'Radiology'), ('Sterilization', 'Sterilization'), ('Laboratory', 'Laboratory'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Surgery', 'Surgery'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Nephrology', 'Nephrology'), ('Apparel', 'Apparel'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies')], max_length=100, null=True),
        ),
    ]
