# Generated by Django 3.0.3 on 2020-02-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200226_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='genericName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Sterilization', 'Sterilization'), ('Nephrology', 'Nephrology'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Surgery', 'Surgery'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Anaesthesiology', 'Anaesthesiology'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Neurology', 'Neurology'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Radiology', 'Radiology'), ('Cardiology', 'Cardiology'), ('Laboratory', 'Laboratory'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Apparel', 'Apparel'), ('Gynecology & Urology', 'Gynecology & Urology')], max_length=100, null=True),
        ),
    ]
