# Generated by Django 3.0.3 on 2020-02-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200226_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Nephrology', 'Nephrology'), ('Laboratory', 'Laboratory'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Apparel', 'Apparel'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Radiology', 'Radiology'), ('Sterilization', 'Sterilization'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Surgery', 'Surgery'), ('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Anaesthesiology', 'Anaesthesiology')], max_length=100, null=True),
        ),
    ]
