# Generated by Django 3.0.3 on 2020-02-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200226_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Neurology', 'Neurology'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Sterilization', 'Sterilization'), ('Nephrology', 'Nephrology'), ('Anaesthesiology', 'Anaesthesiology'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Radiology', 'Radiology'), ('Cardiology', 'Cardiology'), ('Surgery', 'Surgery'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Apparel', 'Apparel')], max_length=100, null=True),
        ),
    ]
