# Generated by Django 3.0.3 on 2020-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200226_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='genericName',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Anaesthesiology', 'Anaesthesiology'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Otology and Neurotology', 'Otology and Neurotology'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Surgery', 'Surgery'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Laboratory', 'Laboratory'), ('Radiology', 'Radiology'), ('Cardiology', 'Cardiology'), ('Sterilization', 'Sterilization'), ('Apparel', 'Apparel'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology')], max_length=100, null=True),
        ),
    ]
