# Generated by Django 3.0.3 on 2020-02-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200226_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='genericName',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Surgery', 'Surgery'), ('Gynecology & Urology', 'Gynecology & Urology'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Cardiology', 'Cardiology'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Apparel', 'Apparel'), ('Anaesthesiology', 'Anaesthesiology'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Radiology', 'Radiology'), ('Laboratory', 'Laboratory'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Sterilization', 'Sterilization'), ('Nephrology', 'Nephrology')], max_length=100, null=True),
        ),
    ]
