# Generated by Django 3.0.3 on 2020-02-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200226_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Nephrology', 'Nephrology'), ('Neurology', 'Neurology'), ('Sterilization', 'Sterilization'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Apparel', 'Apparel'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Laboratory', 'Laboratory'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Anaesthesiology', 'Anaesthesiology'), ('Cardiology', 'Cardiology'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery')], max_length=100, null=True),
        ),
    ]
