# Generated by Django 3.0.3 on 2020-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200226_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Neurology', 'Neurology'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Cardiology', 'Cardiology'), ('Sterilization', 'Sterilization'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Anaesthesiology', 'Anaesthesiology'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Nephrology', 'Nephrology'), ('Apparel', 'Apparel'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery')], max_length=100, null=True),
        ),
    ]
