# Generated by Django 2.1.1 on 2020-02-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200226_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Sterilization', 'Sterilization'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Neurology', 'Neurology'), ('Gynecology & Urology', 'Gynecology & Urology'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Cardiology', 'Cardiology'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery'), ('Apparel', 'Apparel'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Laboratory', 'Laboratory'), ('Nephrology', 'Nephrology'), ('Anaesthesiology', 'Anaesthesiology')], max_length=100, null=True),
        ),
    ]
