# Generated by Django 3.0.3 on 2020-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200227_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Nephrology', 'Nephrology'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Anaesthesiology', 'Anaesthesiology'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Apparel', 'Apparel'), ('Neurology', 'Neurology'), ('Sterilization', 'Sterilization'), ('Cardiology', 'Cardiology')], max_length=100, null=True),
        ),
    ]
