# Generated by Django 3.0.3 on 2020-02-27 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200227_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_created',
        ),
        migrations.AddField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Otology and Neurotology', 'Otology and Neurotology'), ('Cardiology', 'Cardiology'), ('Surgery', 'Surgery'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Radiology', 'Radiology'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Laboratory', 'Laboratory'), ('Neurology', 'Neurology'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Sterilization', 'Sterilization'), ('Nephrology', 'Nephrology'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Anaesthesiology', 'Anaesthesiology'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Apparel', 'Apparel')], max_length=100, null=True),
        ),
    ]
