# Generated by Django 3.0.3 on 2020-02-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20200228_0039'),
        ('inventory', '0011_auto_20200228_0016'),
    ]

    operations = [
    ]
