# Generated by Django 3.0.3 on 2020-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200228_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Gynecology & Urology', 'Gynecology & Urology'), ('Anaesthesiology', 'Anaesthesiology'), ('Apparel', 'Apparel'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Radiology', 'Radiology'), ('Sterilization', 'Sterilization'), ('Neurology', 'Neurology'), ('Laboratory', 'Laboratory'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Nephrology', 'Nephrology'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Cardiology', 'Cardiology'), ('Surgery', 'Surgery')], max_length=100, null=True),
        ),
    ]
