# Generated by Django 3.0.3 on 2020-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ward',
            field=models.CharField(blank=True, choices=[('SH-102', 'SH-102'), ('SH-101', 'SH-101'), ('SH-201', 'SH-201')], max_length=10),
        ),
    ]
