# Generated by Django 3.0.3 on 2020-02-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200226_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthDate',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='homeAddress',
            field=models.TextField(default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hospitalName',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middleName',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Nurse', 'Nurse'), ('Client', 'Client')], default='New', max_length=100),
        ),
    ]
