# Generated by Django 3.0.3 on 2020-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200226_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='maritalStatus',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Legally Seperated', 'Legally Seperated'), ('Widowed', 'Widowed')], max_length=20, null=True),
        ),
    ]
